export const ISS_FETCH_INIT = 'ISS_FETCH_INIT';
export const ISS_FETCH_SUCCESS = 'ISS_FETCH_SUCCESS';
export const ISS_FETCH_FAILED = 'ISS_FETCH_FAILED';

export const GOOGLE_FETCH_INIT = 'GOOGLE_FETCH_INIT';
export const GOOGLE_FETCH_SUCCESS = 'GOOGLE_FETCH_SUCCESS';
export const GOOGLE_FETCH_FAILED = 'GOOGLE_FETCH_FAILED';
