export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const PRODUCTS_FETCH_SUCCEEDED = 'PRODUCTS_FETCH_SUCCEEDED';
export const PRODUCTS_FETCH_REQUESTED = 'PRODUCTS_FETCH_REQUESTED';
export const PRODUCTS_FETCH_FAILED = 'PRODUCTS_FETCH_FAILED';